version: "3"
services:
  db:
    container_name: mydb
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
  
  sensor_sim:
    container_name: sensors
    image: sensor-sin
    links:
      - "db"
    ports:
      - "5000:5001"